GeospatialPython/pyshp

README.md

One of the code samples wasn't rendering correctly.
My editor trimmed trailing whitespace so it's recommended to view the PR with whitespace changes ignored:
https://github.com/GeospatialPython/pyshp/pull/19/files?w=1

Format README code sample

---

shapefile.py

While pyshp is generally good about raising appropriate exceptions, it currently uses `assert()` in two places:
* Possibly corrupted DBF header
* User attempting to write larger value than a field allows for
Not only are these both examples of cases where `assert()` isn't appropriate, they're cases that could lead to data corruption if uncaught... and when CPython is invoked with -O or -OO, `assert()` conditions are never raised.
This patch raises a descriptive ShapefileException in these two cases.

Don't Use Asserts For Runtime Errors

---

README.md

Updated link to "XBase File Format Description"  to address Issue #12: Documentation URL not valid #12.  Link now properly links.  fixes #12

Update link to "XBase File Format Description" in Readme.md

---

shapefile.py

I added an iterative version of `Reader.shapeRecords` since I was running out of memory (and thus segfaulting) when handling a larger file on a Vagrant box.

Added `Reader.iterShapeRecords` to help work with larger files

---

shapefile.py

For shapefiles with values that cannot be cast to float or int in the attributes the lib dies with a ValueError. I think it's cleaner to then set the value to None. This is consistent with how QGIS handles these shapefiles and should not cause much trouble. 
If this causes trouble it's possible to add a flag to either die on error or set to None.

Handle non-parseable values in attributes

---

MANIFEST.in

With pattern in the `MANIFEST.in` file `python setup.py sdist` will include most files included in the git repository (the travis config is skipped).
See: https://docs.python.org/2/distutils/sourcedist.html#manifest
Fixes: #63 & #38

Add MANIFEST.in to include more files in sdist.

---

shapefile.py

Previously, callling `w.record()` had no effect, leading to unbalanced shapefiles.

Add empty record when calling w.record() with no arguments

---

shapefile.py

I'm a shapefile newb, but if you're allowed to delete index 0 of the `self._shapes` list, then `Editor.delete()` doesn't currently allow deleting the zeroth index for any of the `shape`, `part`, or `point` parameters.
This changeset tests whether the parameters are `None` which resolves to `False` if a given parameter is `0`

Fix to allow `Editor.delete()` with 0 parameters

---

.travis.yml
shapefile.py

[This is current failing](https://travis-ci.org/micahcochran/pyshp/builds/155648216) until PR #68 is (or some similar solution) has been merged.  It is good that it is failing because it shows that there is a problem running the doctests.
If PR #68 gets merged (or some similar solution), this issue can be closed and reopened to rerun Travis tests.
I added a few small changes so that the number of failures gets reported to the status code.  Any status code that is zero (0) is Travis considers a success, anything other status code  is a failure.  (In this case the status code is 5 because 5 tests fail.) Also, added that verbosity can be turned off from the function.  So, you can quietly run the doctests by calling `shapefile.test(verbose=False)`.

Add Travis testing.

---

shapefile.py

I noticed that the was an `or` here where there should have been an `and`. 
Looking forward to a new release where `shapefile.Reader('./file')` works without `.shx`.

fixed shape file component detection

---

shapefile.py

Removed type overwriting that prevented and caused error when saving null geometries. 
Fixes issue #76. 
Also cleaned up some redundant type checking that was never used.

Fix to allow saving null geometries.

---

shapefile.py

Changed the mbox calculation to use same structure as zbox, while preserving the intent of setting mbox to zeros in case of no m values. 
In the previous implementation the list of m values was instantiated with a zero, presumably to set an mbox of zeros in case of no m values, but this would eg force the mbox to be 0-30 in a case where the true range was 15-30. Unless there is something I don't know about m values, this should not be the case.

Stop zero from sneaking into mbox calculation

---

shapefile.py

Fixes #23, taking advantage of the dbf header recordlength attribute to improve handling of bad files. 
Also cleaned up confusing dbf header code.

Read correct length of record in case of bad file

---

README.md
shapefile.py

Part of the failures was docs and tests related, other was that the new tests revealed wrong type detection in Py3. Fixed all this.

Updated docs, tests, and type detection error to fix Travis CI failures

---

README.md
shapefile.py

Default test verbosity to False to make it easier to spot the test failures. Partially fixes #54.

Remove test verbosity and add Readme Travis CI testing status icon

---

shapefile.py

This is the requested variant of https://github.com/GeospatialPython/pyshp/pull/81 without the `allow_copy` argument as discussed previously. Please see https://github.com/GeospatialPython/pyshp/pull/81 for more details.

Fix file like objects without seek support not being readable (without allow_copy)

---

shapefile.py

Some testing frameworks and other utilities will print a warning when files are left open at the end of a test. I've added a `close` method to the `Reader` class that closes any files that may have been opened. This `close` method is also called from `__del__` if the `Reader` object is deleted/garbage collected. The warning I was getting is:
```
s = shapefile.Reader(shapefilename)
my_code.py:688: ResourceWarning: unclosed file <_io.BufferedReader name='my_shape.shx'>
```
I'm not super familiar with the internals of `Reader` so there could be a chance that this could break anything returned by the `Reader` that references `shp`, `shx`, and `dbf` files and depends on them staying open.

Add close method to Reader

---

shapefile.py

In both Python 2 and 3, all records containing text values are now immediately decoded and returned as unicode based on the specified encoding. When writing, any unicode is encoded to the specified encoding. The encodingErrors option decides how to handle encoding errors. 
As per the shapefile specs, field names are encoded to ascii only.

Added full encoding read/write support

---

shapefile.py

M values are optional for the PointZ shape type. If a PointZ shapefile did not contain M values, the old code would incorrectly fetch bytes from the next record and store it in the `m` field. For the last record, the code would crash since `f.read(8)` would return an empty string.
In order to fix this, this commit checks whether there are any bytes left (`f.tell() < next1`) when the shape type is PointZ (`11`).

Fix Reader.__shape(self) for PointZ without M values

---

.gitignore
README.md
shapefile.py

Hi there, this PR proposes to add a context manager that makes sure open files are closed properly in the most Pythonic way there is (also see #107).
I've also made some other improvements (at least I think they are ;-), these can be singled out if you don't agree with all of them:
- derive all classes from object (i.e. make them new style classes)
- add convenience mapping "shapeType number" <---> "shapeType string" (keeping old module attributes like `shapefile.POINT`)
- improve closing of individual pieces dbf/shp/shx, I think it's not safe right now, if one of these fails, the rest of them are not closed by `Reader.close()`
I've just started using `pyshp` for shapefile manipulations, thanks for the project! It's so convenient that it's noarch, pure Python and py2/3! ❤️ 
Eventually …

Add context manager to Reader and other improvements

---

shapefile.py

for POINT type, bbox calculation was not used (as rcords don't have bboxes). As a result whole shapefile's bbox wasn't updated. 
I added small fix on that

fixed whole file bbox calculation for POINT type features

---

README.md
changelog.txt
shapefile.py

This fixes a bug when writing to date fields with values of before 1900AD. `datetime.datetime.strftime()` raises an exception when used with dates earlier than 1900AD but it's trivial to just use plain string formatting instead.

Fix date field less than 1900

---

shapefile.py

Fixes #140.
It seems that the maximum number of fields is 2046, as verified by checking `ogrinfo` outputs. Here is an example:
```python
import shapefile
w = shapefile.Writer()
n = 2046
for i in range(n):
w.field("field{0}".format(i + 1), "N", 9, 0)
w.record(*range(n))
w.save('test')
```
if `n` is changed to anything higher than 2046, things break and ogrinfo cannot read the file. This PR raises an exception.

Raise exceptions if too many fields are added

---

shapefile.py

When attempting to write to a shapefile.Writer with BytesIO objects, just like the example, an exception is raised: `ShapefileException: No file-like object available.`. This was fixed by not ignoring the `shx` and `dbf` parameters after checking the `shp` parameter.
When exiting the context manager `with shapefile.Writer`, the BytesIO is closed and a `ValueError: I/O operation on closed file.` is raised when attempting to access the buffer later. I've changed the Writer.close method to only close the file object if the target is a filepath, similar to what the zipfile library does.
PS: This is my first PR ever, I apologise if I did something wrong!

Fixed bugs when dealing with file-like objects

---

README.md

This is the list of contributors found by extracting the contributors
list from git logs up to this point in time.
The command used to extract this information was:
```
git log | grep Author | cut -d'<' -f1 | cut -d' ' -f2- | sort | uniq | sed 's/ $//'
```
Author names containing only email addresses as well as plain user name strings were removed. This pull request addresses the issue in #163 Is it ok like this? If you need an update or something differently please let me know and I will be happy to fix.

Add contributors list to the README file

---

shapefile.py

* Typos:
* lits -> lists
* verticies -> vertices
* optimazations -> optimizations
* fields (line 349) -> field's
* Attribute error (line 382) -> AttributeError
* Grammar
* On lines 347, 489, and 503 the phrasing "and allows to use all the optimazations" is not parallel with the "to ensure" that precedes it.
* Add a comma to separate the last two items in the list on line 351
* Phrasing
* Squish "and allows to use all the optimazations" down to "and to reuse all the optimizations".  "Reuse" just seems like a much more confident word, while "allow" is kind of timid.  Whether this change of vocabulary is an improvement is subjective.  Retaining the original vocabulary and instead cleaning the line up as "and to allow the use of all the optimizations" seemed too long to me.
* More explicitly …

Fix typos, tweak grammar, clarify phrasing, and replace Latin with English

---

README.md
shapefile.py

There are small typos in:
- README.md
- shapefile.py
Fixes:
- Should read `similarly` rather than `similiarly`.
- Should read `appropriate` rather than `appropritate`.
- Should read `elevation` rather than `elavation`.
- Should read `inspecting` rather than `inspecing`.
Closes #218

docs: fix a few simple typos

---

test_shapefile.py

The Debian package build for pyshp failed because there is no network in the build environment.
The tests that download data need to be skipped, for this the `network` marker was added to `test_reader_url()`.

Mark tests requiring network.

---

pytest.ini

Prevents `PytestUnknownMarkWarning` when using the mark to deselect tests.
See also https://docs.pytest.org/en/stable/mark.html, and #230, in which the mark was (very helpfully) introduced.

Register pytest mark “network”

---

.github/workflows/deploy.yml
pyproject.toml
setup.cfg
setup.py

Refer to [setuptools' declarative configuration page](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) for moving the static metadata into `setup.cfg`.
A few other notes:
- Use `pyproject.toml` for [PEP 517](https://www.python.org/dev/peps/pep-0517/) implementation, but keep setuptools as build backend for now
- A universal wheel is now built for both Python 2 and 3 compatibility (using `[bdist_wheel] universal=1`; when py2 is eventually dropped, then remove that section)
- Version is dynamically read from `shapefile.py`
- Remove the various Python 3.x classifiers, and just use Python 3, as this is an unnecessary maintenance classifier as old packages should work fine with future Python versions (Python 2.7 is the sole exception); add a few other classifiers
- …

Convert setup.py to declarative configuration setup.cfg file

---

shapefile.py
test_shapefile.py

This PR enables support for reading/writing with [path-like](https://docs.python.org/3/glossary.html#term-path-like-object) objects, e.g. [pathlib](https://docs.python.org/3/library/pathlib.html) or the [tmpdir pytest fixture](https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmpdir-fixture).

Support path-like objects for reading/writing

---

.github/workflows/build.yml
.gitignore
.vscode/settings.json
README.md
requirements.test.txt

Implements issue #268.  Incorporates PR #267 and PR #265
Summary of changes:
- Unpin Pytest version.
- Add Python slim Docker containers for tags 3.10.13, 3.11.7, 3.12.1, and 3.13.0a2 to the test matrix.  
As for PR #267:
- Drop actions/setup-python, move the matrix strategy forward, pin to the specific patch versions below, and use the matrix to run the action in Python Slim containers (versions 2.7.18, 3.5.10, 3.6.15, 3.7.17, 3.8.18, and 3.9.18)
-  Bump actions/checkout from v2 to v3
-  Don't track my VS Code settings files.
As for PR #265
-   Reformat PyShp usage example with undefined variable in readme.md from >>> to Markdown code literal block, so doctest skips it, as for PR # 265.

Test Pyshp in CI in Python 3.10, 3.11, 3.12 and 3.13 containers.

---

README.md

The code block causing the doctests to fail is a helpful example for users,  but the whole point of it is to use a variable name, which is not defined in the snippet.  
This PR simply removes the >>>s so doctest skips it.
Alternatively, this variable (`filename`) could be defined in the code block.  But then the text of the readme would need to be rewritten to reflect this.
If it is desirable to keep this test, it could easily be added to the pytest tests in test_shapefile.py, at the cost of duplication.

Reformat code block as markdown literal code, so doctest skips it.  Fixes #264

---

.github/workflows/build.yml
.gitignore
.vscode/settings.json
README.md

This is trickier to test than normal, as as far as I can tell Github actions are only run from the master branch (and I've renamed master to main in my fork).  There might be some other bug or subtlety I've missed, but in my fork's main branch I've got the same build.yml file, only targetting the branch from which this PR is coming (in which build.yml targets master).  
This PR is from a branch based on the branch from which I raised my previous PR, #265 so it includes the blocking out of the failing Doctest.  the test results for PyShp are all green on Pythons 2.7, 3.5, ..., 3.9.
https://github.com/JamesParrott/IronPyShp/actions/runs/7545262680/job/20540473529
Summary of changes:
- Drop actions/setup-python, move the matrix strategy forward, pin to the specific patch versions below, and …

Fix PyShp's CI, dropping actions/setup-python, running build.yml Action in Python Docker containers. 

---

README.md
shapefile.py

Investigating #258, I confirmed that single points where not being filtered using the bbox parameter. This is added here by duplicating the coordinates of the point to allow for comparison against bbox. A statement from the manual is also updated (since records and iterRecords methods do not allow spatial filtering).

Add spatial filtering for single points

---

test_shapefile.py

Python 3.8 and greater gives multiple "SyntaxWarning: "is" with a literal. Did you mean "=="?" when running test_shapefile. The relevant instances are updated accordingly.

SyntaxWarning for identity checks in test_shapefile

---

shapefile.py

This commit fixes the following error that happens when I try to do `copy.deepcopy()` on a `Record`:
```
Traceback (most recent call last):
File "/home/midichef/pyshp/test.py", line 12, in <module>
records_deepcopy = copy.deepcopy(records)
...
File "/usr/lib/python3.8/copy.py", line 271, in _reconstruct
if hasattr(y, '__setstate__'):
File "/home/midichef/.local/lib/python3.8/site-packages/shapefile.py", line 735, in __getattr__
index = self.__field_positions[item]
...
[Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded
```
The behavior can be tested with this script:
```
#!/usr/bin/python3
import shapefile
import copy
import pickle
shapefile_path = "shapefiles/blockgroups"
sf = shapefile.Reader(shapefile_path)
records = sf.records()
records_deepcopy = …
```

Fix recursion error when copying Record with deepcopy()

---

shapefile.py

Some programs (e.g., PTV VISUM) export shapefiles in .zip with file extensions being .SHP, .SHX, .DBX. The main branch of this program seeks file extension .shp (lowercase) in the zip file, thus cannot find shapefiles with uppercase extensions. I have made minor modifications to the code to resolve this issue.

Added uppercase file extension compatibility for zip files

---

shapefile.py
test_shapefile.py

Before:
```
file *.py
setup.py:          Python script, ASCII text executable
shapefile.py:      Python script, ASCII text executable, with CRLF line terminators
test_shapefile.py: Python script, ASCII text executable
```
Do the strip:
```
perl -pi -e 's/\s+\n/\n/g' *.py
```
After:
```
file *.py
setup.py:          Python script, ASCII text executable
shapefile.py:      Python script, ASCII text executable
test_shapefile.py: Python script, ASCII text executable
```
Move `shapefile.py` back to dos formatting:
```
unix2dos shapefile.py
```

*.py: Remove trailing empty spaces.

---

README.md
changelog.txt

```
codespell --version
2.2.6
```

README.md and changelog.txt: codespell

---

shapefile.py

They live on in the commit history, if required.

Delete dormant commented code blocks

---

.gitattributes

Don't auto convert 'line endings' of shapefiles and zip archives.

Refine git line endings behaviour

---

.github/actions/test/action.yml
shapefile.py

This reverts commit 2dc17a78c4eb90196b36169e897ec36f55a6223e.
Run on this branch
Instead of plain pytest, run pytest -m "not network"
Filter out pytest tests and doctests requiring internet downloads
Run Ruff format
Make skipping network tests optional

Make flakey network dependent tests optional

---

.github/actions/test/action.yml
.github/workflows/run_tests_hooks_and_tools.yml
.pre-commit-config.yaml
shapefile.py
test_shapefile.py

Run on this branch
Run Network tests in container jobs
Remove type field from Action input
Add description and required fields to Action input.
Add option to Clone repo of copies of files to serve locally in mock remote url tests
Specify shell in action job step
Use actions/checkout instead of git (unavailable in Python slim docker images)
Checkout artefacts repo to ..
Add pyshp_repo_directory input
Serve artefacts on localhost:8000
Specify shell: bash in Github action
Don't curl from localhost - not available in Python slim images (neither is wget)
TRy requesting on localhost in Python non-slim images
Correct path to custom test file
Test local server
Sleep for twice as long after  starting simple Python server
Don't output PyTest version
Swap out remote URLs with stripped path localhost …

Use localhost instead of remote server for network marked tests.

---

README.md
src/shapefile.py
test_shapefile.py

Restore the performance level to that before the refactor of the dbf record writer methods.  Correct the implementations of shape bbox, mbox and zbox calculations.

Python 3.0.0 alpha the last jedtype

---

LICENSE.TXT

```
iconv --from-code=Windows-1252 --to-code=UTF-8 --output=LICENSE.TXT.conv \
LICENSE.TXT
touch -r LICENSE.TXT LICENSE.TXT.conv
mv LICENSE.TXT.conv LICENSE.TXT
```

Transcode LICENSE.TXT from Windows-1252 to UTF-8

---

.pre-commit-config.yaml
pyproject.toml

This replaces isort with ruff check's ["I" rule](https://docs.astral.sh/ruff/rules/#isort-i).
Also, small nits:
- Remove [`tool.ruff.target-version`](https://docs.astral.sh/ruff/settings/#target-version) since it is recommended to use `project.requires-python` instead, which is already [defined](https://github.com/GeospatialPython/pyshp/blob/f083ee8c2c1ea3fde2e3bab9c9748dbd982c40ed/pyproject.toml#L19)
- Expand `tool.ruff.lint.select` with inline comments to describe each rule selected

Replace isort with ruff check "I" rule

---

pyproject.toml
run_benchmarks.py
src/shapefile.py
test_shapefile.py

This enables Ruff's [pyupgrade (UP)](https://docs.astral.sh/ruff/rules/#pyupgrade-up) rule.
The associated fixes are automated (no manual edits) and are either [UP007](https://docs.astral.sh/ruff/rules/non-pep604-annotation-union/#non-pep604-annotation-union-up007) or [UP045](https://docs.astral.sh/ruff/rules/non-pep604-annotation-optional/#non-pep604-annotation-optional-up045).

Enable Ruff pyupgrade (UP) rule
